# Generated by Django 3.2.9 on 2021-11-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=200)),
                ('fastest_time', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('laps', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=200)),
                ('gp', models.CharField(max_length=200)),
                ('session', models.CharField(max_length=200)),
                ('published', models.DateField(auto_now=True)),
            ],
        ),
    ]
